### PR TITLE
Add pretty option

### PR DESCRIPTION
**Pull request by krisselden**

### CODE REVIEW

**Comment by michaelficarra** [comment]
Very nice! This is exactly what I was thinking. Fixes #26.

CI failed because coverage dropped a bit. You can run tests with coverage using `npm run generate-coverage` and then view the report by opening `coverage/lcov-report/index.html` in a browser.

**Comment by michaelficarra** [comment]
Very nice! This is exactly what I was thinking.

**Comment by michaelficarra** [comment]
Woah, I just noticed that it says _I_ authored this file. Can you do an amend with `--reset-author` to correct that?

**Comment by krisselden** [comment]
@michaelficarra yes, I accidentally squashed it into the previous commit after I fixed it, it still had the author and time.  I'll look at the coverage, I suspect maybe I didn't cover the semi() case.

**Comment by krisselden** [comment]
I meant the semi() case, actually I don't think the semi() case should be formatted that way, I was just copying https://github.com/shapesecurity/shift-java/blob/bc9df039b7941c61b2140bba42a2a31c4c8d9bf4/src/main/java/com/shapesecurity/shift/codegen/FormattedCodeRep.java#L46 but I don't think you want `"for(;\n;\n){}"`

**Comment by krisselden** [comment]
All green now, I was trying to follow the java version, but I think it is a mistake to put newline on semi(), I changed it to be just semiOp() and brace().

I know you just wanted to start with this but would you be ok with a follow up PR that just moved the functions that create Tokens and CodeReps to be methods and exporting the CodeGen, CodeRep and Token classes, so they could be customized to say allow indenting?

**Comment by krisselden** [comment]
@michaelficarra I've addressed the two comments, is there something more I need to do?

**Comment by michaelficarra** [comment]
This LGTM. I'd love to also see that PR to shift-java to fix newline generation in `for` heads if you can find the time.

**Pull request merged**
