### PR TITLE
Performance improvement to fix #87

### LINKED ISSUE #87: Performance: degradation linked to generated source size & targeting es2015
Every time another token is added, TokenStream checks the end of what it has already generated to avoid creating an HTML comment ([L:105](https://github.com/shapesecurity/shift-codegen-js/blob/es2018/src/token-stream.js#L105)). This blows up as source size increases. Generating 547k of js takes ~120 seconds on a recent MacBook and with a more focused check it drops to ~4 seconds. Reducing the number of babel transforms drops runtime further to ~0.3 seconds.

I can submit a PR for any combination of the above. Getting rid of the `endsWith()` check is important, but limiting or removing babel would give the best performance gains.

### PR DESCRIPTION
**Pull request by jsoverson**
This PR removes the `endsWith()` check that gets slower as the generated result increases in size and adds special-cased to prevent creating html-style comments.

### CODE REVIEW

**Review by bakkot — APPROVED** [review]

**Comment by michaelficarra** [comment]
Could we have just checked the last two characters using indexing? I imagine that's not slow for long strings, right?

**Comment by bakkot** [comment]
> I imagine that's not slow for long strings, right?

It's going to depend on the string representation. I wouldn't've expected `endwith("constant")` to be slow either (in fact it should be as fast or faster than indexing), but here we are.

**Comment by michaelficarra** [comment]
True, but since we're making this change for entirely practical performance reasons, it seems worth exploring. Who cares why it works if it does and it leads to a simpler implementation.

**Comment by bakkot** [comment]
Since we're doing this for performance reasons, we should do the thing which we are confident should have good performance across the board, rather than the arguably simpler thing which might well have bad performance under some circumstances we have not tested (including possible future changes in engines).

**Pull request merged**
